version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
commands:
   destroy_environment:
     steps:
       - run:
           name: Destroy environment
           when: on_fail
           command: |
             aws cloudformation delete-stack --stack-name nd9991-c3-l4

jobs:
  create_infrastructure:
    executor: aws-cli/default
    steps:
    - aws-cli/install:
        disable-aws-pager: false
    - checkout
    - run: |
        mkdir workspace
        aws cloudformation deploy --no-fail-on-empty-changeset --stack-name nd9991-c3-l4 --template-file template.yml  --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
        aws ec2 wait instance-status-ok
        aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udacity" --output text > workspace/inventory
    - persist_to_workspace:
        root: workspace
        paths:
          - inventory
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints: ["dd:68:51:83:a4:47:35:d3:8c:65:55:66:bb:db:70:bb"]
    - attach_workspace:
        at: workspace
    - run: apk add --update ansible
    - run: ansible-playbook -i workspace/inventory ansible-setup-web.yml
  smoke_test:
    docker:
      - image: cimg/python:3.7
    steps:
    - attach_workspace:
        at: workspace
    - aws-cli/install:
        disable-aws-pager: false        
    - run:
        command: sudo apt install curl
    - run:
        name: smoke test
        command: |
          URL=http://$(cat workspace/inventory):3000
          # Test if website exists
          if curl -s --head -m 30 ${URL}
          then
            return 0
          else
            return 1
          fi
    - destroy_environment
workflows:
  deploy:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          requires:
            - create_infrastructure
      - smoke_test:
          requires:
            - configure_infrastructure