version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  deploy-cloudformation:
    executor: aws-cli/default
    steps:
    - aws-cli/install:
        disable-aws-pager: false
    - checkout
    - run: aws cloudformation create-stack --stack-name nd9991-c3-l4 --template-body file://template.yml  --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
workflows:
  deploy-cloudformation:
    jobs:
      - deploy-cloudformation
